# generated by datamodel-codegen:
#   filename:  oi-invoice.json
#   timestamp: 2025-02-25T05:22:56+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Site(BaseModel):
    itemId: str
    name: str
    code: str


class BuyerParty(BaseModel):
    name: str
    partyDUNS: str
    supplierNumber: str
    secondarySupplierNumber: str
    sites: List[Site]
    registeredSupplier: bool


class SupplierParty(BaseModel):
    name: str
    partyDUNS: str
    supplierNumber: str
    secondarySupplierNumber: str
    sites: List[Site]
    registeredSupplier: bool


class ProductService(BaseModel):
    itemID: str
    code: str
    category: str
    description: str


class TicketLineItem(BaseModel):
    itemId: str
    ticketId: str
    ticketNumber: str
    lineNumber: str


class PurchaseCategory(BaseModel):
    itemID: str
    code: str


class PriceBookPriceEntry(BaseModel):
    priceEntryId: str
    description: str
    isDisputed: bool


class LineItem(BaseModel):
    itemId: str
    lineNumber: str
    detailType: str
    description: str
    productService: ProductService
    serviceDateFrom: str
    serviceDateTo: str
    quantity: float
    rate: float
    unitOfMeasure: str
    discountPercentage: float
    discountTotal: float
    subTotal: float
    taxAmount: float
    totalAmount: float
    ticketLineItem: TicketLineItem
    purchaseCategory: PurchaseCategory
    priceBookPriceEntry: PriceBookPriceEntry


class Invoice(BaseModel):
    invoiceNumber: str
    status: str
    invoiceDate: str
    serviceDate: str
    totalAmount: float
    currencyCode: str
    buyerParty: BuyerParty
    supplierParty: SupplierParty
    isQuickPay: bool
    lineItems: List[LineItem]
    attachmentCount: int
    mostRecentComment: str
    currentOwner: str
    exportDate: str
    paymentDate: str
    resubmittedDate: str
